<?php  //[STAMP] 3e3f328c0cbd93b0385bd3c4c9fdfdc1
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Helper\Couple;

trait CoupleTesterActions
{
   
}