<?php

namespace app\modules\couple\models;

use app\models\ext\WeddingDrink;
use yii\helpers\ArrayHelper;

/**
 * Class DrinkCategory
 * @package app\modules\couple\models
 */
class DrinkCategory extends \app\models\ext\DrinkCategory
{
    /**
     * @return mixed
     */
    public function getDescription()
    {
        return count($this->alcohols) > 0 ?
            implode(', ', ArrayHelper::getColumn($this->alcohols, 'title')) :
            'Click plus on right to add';

    }

    public function beforeDelete()
    {
        $this->unlinkAll('weddingDrinks', true);

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWeddingDrinks()
    {
        return $this->hasMany(WeddingDrink::className(), ['drink_category_id' => 'id']);
    }

    /**
     * @param bool $insert
     *
     * @return bool
     */
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->order = static::find()->count() + 1;
        }

        return parent::beforeSave($insert);
    }
}